name = "pokemon-tcg-history-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "pokemon-tcg-history"
database_id = "56bcb6cd-cfc3-4c63-901c-7237891cbf87"

[observability]
enabled = true
